AWSTemplateFormatVersion: '2010-09-09'
Description: Template to Create an EC2 instance with default parameters
     
Parameters:

    ImageId:
          Type: String
                Description: 'Linux 2 AMI for Ireland eu-west1 Region'
                      Default: ''
                          InstanceType:
                                Type: String
                                      Description: Choosing  t2 micro because it is free
                                            Default: t2.micro
                                                KeyName:
                                                      Description: SSH Keypair to login to the instance
                                                            Type: AWS::EC2::KeyPair::KeyName
                                                                  Default: <give the keypair name from your list of keys>

                                                                  Resources:
                                                                      DemoInstance:
                                                                            Type: 'AWS::EC2::Instance'
                                                                                  Properties: 
                                                                                          ImageId: !Ref ImageId
                                                                                                  InstanceType: !Ref InstanceType
                                                                                                          KeyName: !Ref KeyName

                                                                                                          Outputs:
                                                                                                              DemoInstanceId:
                                                                                                                    Description: Instance Id 
                                                                                                                          Value: !Ref DemoInstance

